version: 2
jobs:
  build-components:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run: mvn clean install -B -DskipTests
    - save_cache:
        key: {{ .Branch }}-{{ checksum "pom.xml" }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - target
        - ~/.m2
    - store_test_results:
        path: target/surefire-reports
  deploy-components:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - restore_cache:
        keys:
        - {{ .Branch }}-{{ checksum "pom.xml" }}-{{.Environment.CIRCLE_SHA1}}
    - run: mvn jar:jar deploy:deploy -B -DskipTests
    - store_artifacts:
        path: target
  integration-test:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - restore_cache:
        key: {{ .Branch }}-{{ checksum "pom.xml" }}-{{ .Environment.CIRCLE_SHA1 }}
    - run: mvn integration-test verify -B
    - store_test_results:
        path: target/failsafe-reports
    - store_artifacts:
        path: target
        
workflows:
    version: 2
    build-push:
      jobs:
      - build-components
      - integration-test:
          requires:
          - build-components
      - deploy-components:
          requires:
          - integration-test