version: 2
jobs:
  build-components:
    docker:
    - image: circleci/openjdk:8u171-jdk-stretch
    environment:
      CC_TEST_REPORTER_ID: 269aef8f8e92ff9098164f7454b5c1b715c1fa5f955f2aaa31770771ee82fd38
    steps:
    - checkout
    - run:
        name: Setup Code Climate test-reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
    - run: mvn clean install -B -s .circleci/settings.xml
    - run:
        name: Upload Code Climate test-reporter
        command: |
          cd ~/project/src/main/java
          ~/project/./cc-test-reporter format-coverage -d -t jacoco ~/project/target/site/jacoco/jacoco.xml -o ~/project/target/coverage/codeclimate.json
          cd ~/project
          ./cc-test-reporter upload-coverage -d -i ~/project/target/coverage/codeclimate.json
    - save_cache:
        key: configrd-client-{{ .Branch }}-{{ checksum "pom.xml" }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - target
        - ~/.m2
    - store_test_results:
        path: target/surefire-reports
  deploy-components:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - restore_cache:
        keys:
        - configrd-client-{{ .Branch }}-{{ checksum "pom.xml" }}-{{.Environment.CIRCLE_SHA1}}
    - run: mvn jar:jar deploy:deploy -B -DskipTests  -s .circleci/settings.xml
    - store_artifacts:
        path: target

workflows:
    version: 2
    build-push:
      jobs:
      - build-components
      - deploy-components:
          requires:
          - build-components
